SELECT USER();

USE test;

SELECT @@tx_isolation;

SELECT @@GLOBAL.tx_isolation;

SET SESSION TRANSACTION ISOLATION LEVEL SERIALIZABLE;

START TRANSACTION;

UPDATE teszt SET mezo1 = 2, mezo2 = 1;
SELECT SLEEP(20);

ROLLBACK;
COMMIT;


SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SELECT * FROM teszt;

SHOW OPEN TABLES;